### ISSUE TITLE
TDVF is reset when vTPM feature and SecureBoot feature are enabled together.

### ISSUE THREAD

**Issue by mxu9** [intel/vtpm-td#60] opened 2023-08-25 01:20 UTC

**Comment by sunceping** [comment] 2023-08-30 08:30
This is not an issue in TDVF.

In UEFI shim loader,  we had found the root cause in [fallback.c](https://github.com/rhboot/shim/blob/main/fallback.c) and the  [commit](https://github.com/rhboot/shim/commit/431b8a2e75a71a0b1f47d47d3f045b1e3efbce53).
Now, the reset would happen under two conditions:
•	fallback_should_prefer_reset()  is true (tpm is present)
•	get_fallback_no_reboot() is false (= FB_NO_REBOOT shim efi var is not set Or not equals 1)(this var is not set by default)

For this issue , we can ref the link [Obsolete fallback.efi](https://github.com/rhboot/shim/issues/429), that should be fixed by shim16.

Now we can set up the shim var to avoid reset before shim16 fixes the issue.

**Comment by sunceping** [comment] 2023-08-31 03:22
We can use the tools [(ovmfkeyenroll)](https://github.com/intel/tdx-tools/blob/tdx-1.5/utils/ovmfkeyenroll/ovmfkeyenroll/var_enroll.py) to set the shim var in the fd.
Before setting the variable, we need to create a file like  NO_REBOOT_enable.bin (same with [SecureBootEnable.bin](https://github.com/intel/tdx-tools/blob/tdx-1.5/utils/ovmfkeyenroll/ovmfkeyenroll/SecureBootEnable.bin))

Example command:
python var_enroll.py --fd OVMF.fd -op add -n FB_NO_REBOOT -g 605dab50-e046-4300-abb6-3dd810dd8b23 -a 0x7 -d NO_REBOOT_enable.bin -o OVMF_NO_REBOOT.fd

**Closed** 2023-09-01 01:37 UTC
